# -*- coding: utf-8 -*-
"""Astrobiology Notes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4k1Agu0pKsN844o94YS8qgF_fD5xrGn

## **Astrobiology Notetaking I**
**--ralph--**
###Planets derived from the Greek word πλανήτης(planetes, which is the term for wandering stars). Many ancient civilizations would use a written language to  describe many events that would take place within the celestial world. 

###The rings of Saturn are not primodial. The planet had a possible collision with a previous moon that became what is now known as its famous rings. 

###Analysis of comet G7P revealed that Earth's water did not come from foreign bodies, but was present at formation. This was done by comparing the Deuterium/Hydrogen ratio (D/H ratio). The D/H ratio of comets matches water on Mars, but differs considerably from water present on Earth.

###Astronomers research exoplanets and their ability to formulate the possibility of there to be life on other planets. These requisistions happen to be based on their mass, how close they are to their star, their orbits, radii, and golden zones. 

###Onto biology, they study the aspect of how life can survive. For example would be the life that is able to survive in the depths of the ocean off of thermonuclear energy collection. 

##$$*Solar * System* $$
- ### The solar system  is dominated by a single objection, which is our Sun. The sun is fat and uses its gravity to hold its 4.571 billion year old debris in its orbit. 

## $$*Giant * Planets*$$
- ### The two major giant planets (Saturn and Jupiter), consist of strong gases that are just nasty and deadly.

- ### Neptune and Uranus are ice giants. Brrr! Is it cold over there, am I right? Pretty sure it rains diamonds on Uranus or something. 

## $$*Terrestrial * Planets*$$
- ### Earth and Venus happen to be the two largest with defined atmospheres.
- ### Earth and Mercury have an internally generated magnetic field. 
- ### Mercury has the thinnest atmosphere, Venus has the thickest. 

## $$*Minor * Planets * and * Comets* $$
- ### The Kuiper belt consists of a thick disk of small bodies beyond the orbit of Neptune. These bodies are composed of a mixture of ice and rock, where the two largest members are Eris and Pluto (see what's going on here?)  A minor planet include asteroids, as well as distant minor planets.

- ### Comets are ice-rich objects that shed mass when subjected to solar heating. Comets may have formed near the giant planet region initially, were transported and stored in the Oort Cloud, Kuiper Belt, or the scattered disk.

## $$Satellite * and * Rings* Systems$$
- ### Mercury and Venus are the only two planets in the solar system without natural satellites. 

- ### All major satellites (except Triton) orbit in the direction of the host planet's rotation (i.e. prograde). 

- ### Venus and Uranus are the only two planets that move in retrograde.

- ### Each of the giant planets have rings!

## $$Heliosphere$$
- ### The planetary orbits that lie within the region of space containing the Sun's magnetic fields and ionized gas. The solar wind consists of plasma that could set our tech back by a hundred years at least. 

## **$$What * is * a * Planet?$$** 
- ### **Planet**: A celestial body that orbits the Sun, has a sufficient mass to assume a nearly round shapeshape through its self-gravity, and has cleared its orbital neighborhood of similar sized-bodies.

- ### **Dwarf Planet**: A celestial body that orbits the Sun, has sufficient mass to assume a (nearly round) shape through its self-gravity, has not cleared its orbital neighborhood of similar sized-bodies, and is not a satellite. 

- ### **Star**: A self-sustaining (proton; proton chain) fusion is sufficient for thermal pressure to balance gravity.

- ### **Stellar remnant**: no more fusion (dead star)

- ### **Brown dwarf**: substantial deuterium (proton + neutron) fusion, where more than of the object's original deuterium inventory is destroyed by fusion.
- ### **Planet**: negligible fusion, with a precise mass limit depending on the initial composition. It can orbit one (or more) stars, a stellar remnant, or no stars at all.

**-Kisten-**

##$$A * Brief * History$$
###The study of Astronomy existed long before there was even a name for it. Many ancient civilizations even knew of the existance of planets and wrote about them. These civilizations also used the planets and stars to help them navigate. As civilization advanced, new technological advances allowed us to see and learn more about space. They allowed us to see a different view of the Moon (Luna 3). They also allowed us to find planets outside our own solar system (Kepler and T.E.S.S), and helped put to rest some theories about Earth itself (Earth's water didn't come from comets).

## $$Our * Solar * System*$$

- ### The Sun contains almost all of our solar system's mass.

- ### The Sun is a plasma ball powered by fusion.

- ### Compared to the Sun, the planets are debri.

## $$Giant * Planets$$

- ### Jupiter is 318 Earth masses while Saturn is 1/3 of Jupiter's mass.

- ### Both Jupiter and Saturn are composed mostly of H2 and He.

- ### Uranus is 14 Earth masses and Neptune is 17 Earth masses.

- ### Uranus and Neptune are mainly composed of water, ammonia, and methane ices.

## $$Terrestial * Plantes$$

- ### They are made up of silicates and many chemicals.

- ### Earth and Venus are the largest two and are similar in size.

- ### Mars is smaller than Earth.

- ### Mercury is very tiny compared to the others.

- ### They each have a varied atmosphere.

- ### Earth and Mars have a magnetic field.

## $$Minor * Planets * and * Comets$$

- ### The Kuiper belt is a thick disk of small bodies, it is mainly composed of rock and ice.

- ### Eris and Pluto are the largest of the bodies in the Kuiper belt.

- ### Pluto and Neptune have a crossing orbit, but never collide.

- ### The objects in the Kuiper belt can only be observed at their perihelion due to darkness.

- ### **Comets -** ice rich objects that can originate from the Asteroid belt or the Kuiper belt.

## $$Satellites * and * Rings$$

- ### All the Gas Giants have rings and satellites.

- ### Mercury and Venus are the only planets to not have a natural satellite.

- ### Saturn has the most pronounced rings.

- ### Jupiter has very faint rings due to its moons using up most of its material to form.

## $$Heliosphere$$

- ### This is the region the Sun's solar winds act on.

- ### The area it merges with the Interstellar medium is the heliopause.

- ### Voyager 1 and 2 have gone beyond this region.

- ### The local Interstellar medium is mostly composed of H and He.

## $$What * is * a * Planet?$$

- ### **Planet -** orbits the Sun, has mass to assume a near round shape, and has cleared its orbital field.

- ### **Dwarf Planet-** does all that a normal planet does except clear its orbital field of debris. It also can't be a satellite.

- ### **Star -** suntains fusion (proton fusion)

- ### **Stellar Fusion -** does not have any fusion left

- ### **Brown Dwarf -** sustains deuterium fusion

- ### **Planet -** has neglible fusion




**--Grayson--**

###We get the word "Planet" from the Greek word "planetes"

###All planets were visited by spacecraft during the cold war.

###EM Spectroscopy allows us to study the atmosphere and geology of most celestial bodies

###Analysis of comet G7P revealed that Earth's water did not come from foreign bodies, but was present at formation. The Deuterium/Hydrogen ratio (D/H ratio) of water allows us to compare sources of water. The D/H ratio of water on comets compares to mars, but is not similar to water present on Earth, suggesting different origins.

###M⊕ represents units of Earth mass
###M☉ represents units of Solar mass
###R🜨 represents units of Earth radius
###R☉ represents units of Solar radius
###AU represents astronomical units, the length of the semimajor axis of a massless particle whose orbital period is 1 year


###Jupiter is roughly 318 Earth Masses and 9.54•10^-4 Solar masses

###The astrophysical ices are Water (H2O), Ammonia(NH3), and Methane (CH4)

###Earth, Venus, Mars, and Mercury are terrestrial planets. Mercury has an atmosphere by definition, although it is essentially just a thin layer of surface particles kicked up by solar winds. 

###Kuiper belt objects, like Pluto and Eris, are mixtures of rock and ice, and have eccentric orbits. They are so far away that we can only observe them at perihelion. The alignment of orbits in the outer solar system suggest that many of these objects are orbiting an unknown body beyond Neptune that may be as large as 5 Earth masses. 

###comets are ice-rich objects that shed mass when subjected to solar heat

###zodiacal particles are particles in planetary orbital rings

###all major satellites (but triton) orbit in the direction of the host's rotation

###all gas giants have rings, Jupiters rings are faint and spread out. This is primarily due to Jupiters large and numerous moons.

###Planets 1: orbit the sun, 2: are nearly round due to self-gravity, and 3: have cleared orbital neighborhood

###Dwarf planets are objects that fit the definition of a planet but have not clearied the orbital neighborhood

###stars have self sustaining proton fusion
"""

